### ISSUE TITLE
Useless with perl-mode due to lots of missing operators

### ISSUE THREAD

**Issue by pstray** [davidshepherd7/electric-operator#104]
Lots of operators are missing from perl-mode, so writing things like $foo->{bar} is impossible (it expands to $foo - > {bar}).  

Other operators like --, ++, **, !~, <<, >>,  <=>, ~~, ^^, //, .., ... are missing too.  There is also a problem with writing <>.

**Comment by davidshepherd7** [comment]
Actually I had a quick go. Can you try current master out?

I didn't do anything with `<>` or `^^` yet because I didn't have time to figure out what it is.

I didn't do anything for `..` and `...` because the spacing around them seems to be a matter of taste (I saw both spaced and unspaced in docs).

**Comment by pstray** [comment]
"<>" is the glob operator or reading from a filehandle, don't think it needs spaces around it, as it usually is within a list context like (<>) or part of a scalar assignment like $foo = <>.  But it should definitely not have a space put in after < as it does now ;)

^^ is logical xor, so should be handle the same as || and &&.

.. and ... is seen both with and without spaces, but if people want to use this mode, I guess they would want spaces around .. and ... too :)

I'll have a look the current master when I get home to the computer I tested with :)

**Comment by pstray** [comment]
Seems to be working better, but there still are some issues.

- You don't want space around % if followed by { or $, as in `keys %$foo` and `keys %{$foo[5]}`.
- ** removes spaces before and won't let me type space after it (it is the exponential operator)
- ++ and -- leaves a space after it, usually you wouldn't want that since it is often just before ; or inside ()
- !¯ should be like =~

Other than those it seems to work pretty well

**Comment by pstray** [comment]
I had a look at the code, and it seems `&=`, `&&=`, and `||=` are missing. `|.`, `&.`, and `^.` should have space around them.
I also note that `$foox=` expands to `$foo x=` which probably isn't what we want.

**Comment by davidshepherd7** [comment]
Hey, I think I've added sensible handling of all of those cases. Thanks for testing!

Unfortunately I had to disable handling of `%`, `/`, `x`, `<`, and `>` because they are too hard to implement support for.

I think `%` is possible but it would be tricky and there's bug in the ecukes testing framework that prevents me from writing tests for it :disappointed:

The others... I think I would need to write a full-on perl parser to handle them well :stuck_out_tongue: 


Let me know if you find any other issues!
