### ISSUE TITLE
Python3.x Updates

### ISSUE THREAD

**Issue by gopar** [davidshepherd7/electric-operator#48]
For Python3, there is the typing module

Due to this the package should allow for the following:
```python
def something(x: str) -> str:
    return x
```

But due to how packge is implemented it get stuck as this:
```python
def something(x:str)->str:  # No spaces between func definition and return type
    return x
```

The `->` type can be fixed by adding a rule but the func def looks like it should be changed a bit. Thoughts? Love the package \o/

**Comment by gopar** [comment]
The way I'm currently getting around this is by this

```lisp
;; Create new func
(defun python-mode-in-definition? ()
  "Are we being defined in method/function?"
  (looking-back-locally  "def .*"))

(defun python-mode-: ()
  "Handle python dict assignment"
  (cond
   ((python-mode-in-lambda-args?) ": ")
   ((eq (enclosing-paren) ?\{) ": ")
   ((python-mode-in-definition?) ": ") ;; add it in the check
   (t ":")))
```

**Comment by davidshepherd7** [comment]
Hi, thanks for letting me know about this.

Should be fixed by [this commit](https://github.com/davidshepherd7/electric-operator/commit/573db7ee7d1ed33ac5c047ca0184e4b9f4a11ec3), let me know if anything doesn't work. I basically used your code, except with an additional check that we are inside parens (otherwise it would add a space after the `:` at the end of the line) .

Am I correct in thinking that types can only be declared for function arguments and return values? So there's no new syntax anywhere else?

**Comment by gopar** [comment]
Looks like you can also use types in variables: 

http://www.daveoncode.com/2017/03/06/writing-better-software-with-python-3-6-type-hints/

**Comment by davidshepherd7** [comment]
Ah, yeah. That looks like it will be quite a pain to handle correctly because there is nothing distinguishing a line like `a: ` from a line like `except a:` or `if a:` except for the absence of a keyword. For now I've changed the rule so that electric-operator won't do anything to `:` unless it's sure about what it represents (currently it handles dicts, lambdas, and type declarations in functions.

Can you give it a try and let me know if you come across any problems?

**Comment by gopar** [comment]
Hey, just a quick update.

Everything seems to be working fine and has eased my work. Thanks! :D

**Comment by davidshepherd7** [comment]
Great :) Thanks for letting me know.
