### ISSUE TITLE
Allow using regex to specify symbols

### ISSUE THREAD

**Issue by tuhdo** [davidshepherd7/electric-operator#50]
I want `electric-operator` to reliably adjust my symbols. However, the current rule system only allows plain string. For example, whenever I enter `if`, I want it to become `if `. Currently, if I have a variable named `diff`, it also becomes `dif f`. That's why regex would solve these cases by specifying a regex that matches a symbol like `if`.

**Comment by davidshepherd7** [comment]
I think you can hack this behaviour in at the moment by creating a rule something like

    (cons "if" (lambda () 
                       (when (looking-back-locally "\b")
                           "if "))

I haven't done a very good job of documenting it, but the cdr of a rule can be a function which is called with point just before the operator that was matched. If the function returns nil nothing happens, if returns a string the matched operator (and any existing whitespace) is replaced with the string.

The problem with this will be when you want to type something like `iffy` you would get `if fy`. This would still happen if you could use regexes for the initial match. This isn't usually a problem for operators because (in most languages) you can't have operators as part of other identifiers. This assumption is quite important

**Comment by davidshepherd7** [comment]
I'm closing this for now because it can be done quite easily at the moment using a function and because I don't think it would be particularly useful.

If you still think regexes would be useful feel free to reopen this issue.
