### ISSUE TITLE
Enforces right-hand-style pointer operator in C

### ISSUE THREAD

**Issue by PopeLevi** [davidshepherd7/electric-operator#6]
Not a biggie, but when coding in C/C++, the right-hand-style pointer operator is enforced:

    // Gross.
    void do_something(int *x)

Which is the opposite to my preferred style - left-hand-style

    // Better.
    void do_something(int* x)

Also, when dealing with references in C++, there is whitespace on both sides of the `&` operator:

    // Just no.
    void do_something(const Thing & t)

Like I say, this is not a biggie, but it is enforcing certain programming styles which I (and I assume others) do not agree with

**Comment by davidshepherd7** [comment]
For the pointer style issue: yep that's something that I wasn't sure what to do with. I'll add an option to choose which side the `*` should go. 

Unfortunately cases like 
```
    f(Thing& t)
```
are much (much) harder. The problem is that it's impossible to tell for sure whether `Thing` is a type without doing some real parsing. In the example if `f` is a function declaration then `Thing&` is a type. But if `f` is a function *call* then `Thing & t` is a bitwise-and operation! There is the same issue for pointer types in function declarations vs multiplication in function calls.

At the moment I'm using c-modes `c-primitive-type-key` regex to look for types, which is why it works for `int*`. I'm considering checking for CamelCase, which seems to be a strong convention for C++ class names.

**Comment by davidshepherd7** [comment]
That should fix your first issue, let me know if there are any other problems.

I've opened a separate issue for the second problem [here](https://github.com/davidshepherd7/electric-operator/issues/7) because I suspect it will be much more difficult to fix.

**Comment by davidshepherd7** [comment]
@PopeLevi I've fixed the second issue for examples like the you gave (by using some stuff from `cc-mode`). Unfortunately there's still things like `Thing* my_thing;` which I can't handle that way.

**Comment by PopeLevi** [comment]
@davidshepherd7 This fix works fine. Thanks a bunch :)
