### ISSUE TITLE
bug for org-mode

### ISSUE THREAD

**Issue by c02y** [davidshepherd7/electric-operator#66]
There is a bug for org-mode, I've tested it only requring electric-operator mode for org-mode.

This is all my configuration:

    (require 'electric-operator)
    (add-hook 'org-mode-hook #'electric-operator-mode)

When you type symbol "," or "." symbol at the end of **any** list in org-mode, Emacs will delete all the whitespace between the cursor the next non-whitespace line. 

The screenshots before and after, type at the list number 3 of the first list:
![screenshot_2018-04-16_13-57-47](https://user-images.githubusercontent.com/2135996/38792183-57f70052-417e-11e8-997a-349e759a7047.png)
![screenshot_2018-04-16_13-58-02](https://user-images.githubusercontent.com/2135996/38792293-e1925d98-417e-11e8-953b-205dfdd971c4.png)

**Comment by davidshepherd7** [comment]
That's very strange! Thanks for reporting it, I'll try to have a look sometime soon.

For now you could work around the issue by setting `electric-operator-enable-in-docs` to `nil` when in org mode.

**Comment by davidshepherd7** [comment]
Should be fixed on master now, I'll make a melpa-stable release after I've used it for a while. The issue was that text-mode (and org-mode) consider newlines to have whitespace syntax, which means that the regex class `\s-` matches newlines. This isn't the case in programming modes.

I don't really use it in text modes, which is why I never found this bug.

Thanks again for reporting it :+1:
