### ISSUE TITLE
Can't insert space before closing paren in haskell mode

### ISSUE THREAD

**Issue by andreas-roehler** [davidshepherd7/electric-operator#72]
With cursor at the closing paren at end of  haskell example-code:

foo = map f [1..7]
           where
           f n = if (mod n 2 ==)

AFAIU electric-operator-post-self-insert-function deletes the space inserted by a replace.

**Comment by davidshepherd7** [comment]
Yeah, I recently wrote some Haskell and the support isn't anywhere near as good as I thought it was :disappointed: (I mostly developed it by working against unit tests and talking to the person who requested the feature).

I'm actually considering dropping support because it's a very difficult language to handle. The code for Haskell is already significantly more complex than any other language.

**Comment by davidshepherd7** [comment]
Haskell support has been removed now, so I'll close this issue.
