### ISSUE TITLE
Simplify electric-operator

### ISSUE THREAD

**Issue by andreas-roehler** [davidshepherd7/electric-operator#75]
Opening this for a general discussion. For example these lines in `electric-operator-post-self-insert-function`:

```
(when (derived-mode-p 'haskell-mode)
      (electric-operator-haskell-mode-fixup-partial-operator-parens operator-just-inserted))
```
IMHO there is no chance to get grip on things that way, it runs into the infinite.

Lets start from a true generic setting if possible, than add per-mode setting, then special customsTstyles and so on. Make it do the right thing from the spot, not correct afterwards.

**Comment by andreas-roehler** [comment]
Getting rid of `electric-operator--mode-rules-table`. Can't look inside, which makes debugging harder. Also it contains stuff for all modes AFAIU, which isn't needed. Suggest the use of a simple list containing known operator-characters on a per-mode base. Instead of replacing fixed strings, lets look before and after then, should some whitespace be needed.

**Comment by davidshepherd7** [comment]
Yeah this is why I'm considering dropping support for Haskell, the prefix/infix and partial evaluation stuff is too complicated to handle within the normal electric-operator framework.

> Getting rid of electric-operator--mode-rules-table. Can't look inside, which makes debugging harder. Also it contains stuff for all modes AFAIU, which isn't needed. Suggest the use of a simple list containing known operator-characters on a per-mode base.

Do you mean the fact that it's a trie? The 1.0 branch uses an alist so you're welcome to use that if you prefer. The reason I changed it to a trie is that you get a big performance improvement (that's important because this runs after every self-insert-command). 

If you're interested in making it easier to debug you could probably write a function that prints a trie in a simple format. That would be a nice feature to have :slightly_smiling_face:.

In general: I don't think I'll be doing any major refactorings to the internals of electric-operator any time soon, I have plenty of other things to work on and it works well for me. Most of the data structures are the way they are for good reasons. You're welcome to try some refactorings, and if you can get tests passing, comparable performance and no breaking changes with simpler code I'd be interested in merging your work.

**Comment by andreas-roehler** [comment]
As a first step I'd like to reorder the stuff a little bit. As you will be aware, the start and end of a file a most easy to reach and read. Therefor let's put the most importend parts there. Convention is to start with defcustom and other var setting and end with mode.

**Comment by davidshepherd7** [comment]
Opened #88 for the pretty printer, I'll also look into dropping haskell support which would remove a lot of the complexity.
